
server:
  port: 9009

spring:
  application:
    name: user
  datasource:
    url: jdbc:mysql://192.168.9.122:3306/bladex_sword?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: 123456

#mybatis:
#  type-aliases-package: org.ec.test.entity
#  mapper-locations: classpath:org.ec.test.mapper/*.xml

mybatis-plus:
  mapper-locations: classpath:org.ec.test.mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: org.ec.test.entity
  #typeEnumsPackage: org.springblade.dashboard.entity.enums
  global-config:
    # 关闭MP3.0自带的banner
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: 0
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: 2
      #驼峰下划线转换
      column-underline: true
      # 逻辑删除配置
      # 逻辑删除全局值（1表示已删除，这也是Mybatis Plus的默认配置）
      logic-delete-value: 1
      # 逻辑未删除全局值（0表示未删除，这也是Mybatis Plus的默认配置）
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false


logging:
  level:
    org.ec.test.mapper: ERROR
    root: INFO

info:
  version: easy.test.1.0
  desc: ${spring.application.name}









